### ISSUE TITLE
Two or more inverters

### ISSUE THREAD

**Issue by tompsg-git** [kbialek/deye-inverter-mqtt#102]
Hello,
would it be possible to add more than one inverter at a time without starting two container?
Thanks, 
Thomas

**Comment by kbialek** [comment]
Hi. No, this is not planned. Out of curiosity, what is your use-case?

**Comment by tompsg-git** [comment]
I have three solar panels on separate places each with a own inverter because of many trees around. Two of them are Bosswerk MI300 (Deye).

**Comment by kbialek** [comment]
Okay, but why running two containers is not a good option for you?
