### ISSUE TITLE
Deye SUN-20K-SG01HP3-AM2 Support

### ISSUE THREAD

**Issue by Verkalets** [kbialek/deye-inverter-mqtt#104]
- Inverter model: Deye SUN-20K-SG01HP3-AM2

Hi, I'd like to check if Deye SUN-20K-SG01HP3-AM2 will be supported? Is the any chance to do it before installation?

**Comment by kbialek** [comment]
Hi! So far no one reported this inverter as compatible, so I can only make an educated guess here. Imho, most likely it will not work out of the box. This is a 3 phase hybrid inverter from SG01 product line. As for now, this tool supports SG01LP1 1 phase hybrid inverters (deye_hybrid) and SG04LP3 3-phase inverters (deye_sg04lp3).

**Comment by Verkalets** [comment]
@kbialek Thank you for explanation!

**Comment by kbialek** [comment]
@Verkalets Perhaps it's something interesting for you https://github.com/kbialek/deye-inverter-mqtt/issues/41#issuecomment-1636741106

**Comment by kbialek** [comment]
@Verkalets Please read this thread #110
