### ISSUE TITLE
Active Power Regulation

### ISSUE THREAD

**Issue by itboxtrier** [kbialek/deye-inverter-mqtt#114]
Hi,

i want to throttle the inverter dynamicaly via the Active Power Regulation. 
The Question, is it a eeprom write? so after a time the dynamic regulation will kill the inverter?

**Comment by kbialek** [comment]
I have no knowledge about the inverters' hardware and design, so I'm not able to answer this question. You should rather ask Deye support about that. From my experience with electronics I can say that, EEPROM is not the only possible option. Other alternative is a battery backed RAM, or a combination of both RAM and EEPROM with automatic data backup to EEPROM in an event of AC or DC power loss.
