### ISSUE TITLE
Micro inverter temperature sensors

### ISSUE THREAD

**Issue by kbialek** [kbialek/deye-inverter-mqtt#13]
@Antagor Could you please describe here the temperature formulas that shall be used for your microinverter?

**Comment by Antagor** [comment]
Great!!! it's running fine.
actual debug log for temp:
2023-01-06 13:45:00,876 - DeyeDaemon - DEBUG - Radiator temperature: 159.0
2023-01-06 13:45:00,877 - DeyeDaemon - DEBUG - IGBT temperature: -100.0
Read Value 0A1E = 2590
radiator_temp_sensor = SingleRegisterSensor("Radiator temperature", 0x5a, 0.01,
                                            offset=-10, mqtt_topic_suffix='radiator_temp')
2590 * 0,01 = 25,90 -10 = 15,90C sounds suitable for me. Much more than 160C at 11C weathertemp and no sun...
I don't understand, wrong word - know, all the syntax you add for the group, but i can read it and it sound good (;-)
