### ISSUE TITLE
How to run plugin from docker image

### ISSUE THREAD

**Issue by fakehec** [kbialek/deye-inverter-mqtt#135]
Hi,

I have a working installation of deye-inverter-mqtt.

I have followed the guidelines to star the docker image with the plugins directory.

I haver downloaded stdout-publisher to the plugins directory.

How to run the docker file to use a plugin?

Regards.

**Comment by kbialek** [comment]
@fakehec It's documented here https://github.com/kbialek/deye-inverter-mqtt#how-to-start-the-docker-container-with-custom-plugins

`./plugins` is the path to the directory where you put the plugin file

**Comment by fakehec** [comment]
Yes, i read it. My question is how to make the docker program to run the plugin, as for example stdout-publishing.

**Comment by kbialek** [comment]
You do not have to anything more. If the plugins directory is mounted correctly, you should see log messages similar to these
```
2023-11-15 21:04:48,754 - DeyePluginLoader - INFO - Loading plugin: 'deye_plugin_sample'
2023-11-15 21:04:48,754 - DeyePluginLoader - INFO - Loading custom event processor: 'sample_publisher'
```

**Comment by fakehec** [comment]
Thanks a lot
