### ISSUE TITLE
Multiple inverters possible?

### ISSUE THREAD

**Issue by GerhardLang** [kbialek/deye-inverter-mqtt#136]
**Hardware (please complete the following information):**
 - Inverter models Deye800 and Deye1600 (microinverters) 12 pcs.

**Software (please complete the following information):**
 - Logger firmware version: actual
 - deye-inverter-mqtt version: actual

Hello. Can I query multiple inverters with one instance of deye-inverter-mqtt?

Thank you.
Gerhard

**Comment by kbialek** [comment]
No, you need to start one docker container for each inverter you have.

**Comment by GerhardLang** [comment]
Thank you, no problem, I supposed this but hoped :-)
