### ISSUE TITLE
Support multiple batteries if possible

### ISSUE THREAD

**Issue by c0ldtech** [kbialek/deye-inverter-mqtt#162]
Currently only one batterie is supported, i.e. you only get the overall values if you have multiple batteries. 

For example:

Battery 1 SOC is 20%
Battery 2 SOC is 40%

The value shown for battery SOC will be 30%.

In the Solman app it's possible to view the actual values for every single battery.

I don't know if the values per battery are even exposed through modbus, so it might not be possible to actually get the values.
If testers are needed to try stuff out, I'd be happy to help!

Thanks for all the work so far!

**Comment by kbialek** [comment]
What is your inverter model?

**Comment by c0ldtech** [comment]
Sorry, completely forgot to mention this. It's a Deye SUN 10K-SG04LP3 with two Deye SE-G5.1 Pro batteries.

**Comment by kbialek** [comment]
Try out metric group [deye_sg01hp3_battery](https://github.com/kbialek/deye-inverter-mqtt/blob/main/docs/metric_group_deye_sg01hp3_battery.md) instead of [deye_sg04lp3_battery](https://github.com/kbialek/deye-inverter-mqtt/blob/main/docs/metric_group_deye_sg04lp3_battery.md). SG01HP3 and SG04LP3 have similar register layout.

**Comment by c0ldtech** [comment]
Unfortunately, that doesn't seem to have worked. The values that were shown as overall values for both batteries under "battery" are now shown under "battery/1" (and power and voltage are wrong by a factor of 10), values for "battery/2" are all 0.

**Comment by kbialek** [comment]
I found this, maybe it will work. Try to read the registers using the command documented here https://github.com/kbialek/deye-inverter-mqtt?tab=readme-ov-file#reading-and-writing-raw-register-values

![image](https://github.com/kbialek/deye-inverter-mqtt/assets/1640028/43d77a97-b8ff-42cc-8fc9-f61f3e318e8a)
![image](https://github.com/kbialek/deye-inverter-mqtt/assets/1640028/bc6601d1-6705-4e5e-8d7e-f0e07be0ce30)

**Comment by c0ldtech** [comment]
So I should do "r 600" to get the value for Module Voltage? I do get values, but none of the registers I tried make sense, the values do not match with anything expected. But it's good to know that I can try some stuff out this way, I'll try to do some trial and error if I find the time.

**Comment by kbialek** [comment]
> So I should do "r 600" to get the value for Module Voltage?

Yes, exactly

In the doc I have, the 1st battery pack address is 600, the 2nd pack address is 614, the 3rd starts at 628, and so on, up until pack 15 starting at 800. Good luck!

**Comment by kbialek** [comment]
Perhaps your batteries are mapped as packs other than 1 and 2? How is the solarman app showing the metrics?

**Comment by c0ldtech** [comment]
I already tried the values for pack 15, but basically everything has a value of 0 there. 

I'm currently inclined to think that either they do not have the packs exposed through modbus, or it is just not supported for my battery configuration (even though I am using Deye batteries).
