### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by mluckas** [kbialek/deye-inverter-mqtt#167]
When I try to run the code I get several errors like that: 
File "/home/pi/deye-inverter-mqtt/src/deye_config.py", line 68, in DeyeEnv
    def string(env_var_name: str, default_value: str = None) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by kbialek** [comment]
Looks like a duplicate of https://github.com/kbialek/deye-inverter-mqtt/issues/128
