### ISSUE TITLE
Add "time of use" configuration for Deye High Voltage inverters

### ISSUE THREAD

**Issue by aperiodicchain** [kbialek/deye-inverter-mqtt#170]
Hi, 
in #132 "time of use" has been added for Deye LV inverters.
Although Deye HV inverters are generally supported (metric_group_deye_sg01hp3), "time of use" currently is not.

I have tried `metric_group_deye_sg04lp3_timeofuse` on my HV and it works pretty well, so let's add `metric_group_deye_sg01hp3_timeofuse`

Before committing, can someone please confirm my findings?

- unit of Time of Use Power 1-6 is 10W, in contrast to W in the LV settings
- Time of Use Voltage 1-6 I can't make sense of. Even if the unit would be 0.1V, what would 290V mean? The only similar value I could find in my BMS is MIN. Discharge Voltage = 290V (I have 3 modules a 100V so nominal Voltage 307V)

I am attaching screenshot + corresponding readings:

| SUT                                 | Modbus address | ?Unit | response | test result |
| ----------------------------------- | :------------: | :---: | -------- | ----------- |
| Time of Use Weekly Selling Schedule |      146       |       | 255      | Pass        |
| Time of Use Time 1                  |      148       |       | 100      | Pass        |
| Time of Use Time 2                  |      149       |       | 500      | Pass        |
| Time of Use Time 3                  |      150       |       | 900      | Pass        |
| Time of Use Time 4                  |      151       |       | 1300     | Pass        |
| Time of Use Time 5                  |      152       |       | 1700     | Pass        |
| Time of Use Time 6                  |      153       |       | 2100     | Pass        |
| Time of Use Power 1                 |      154       |  10W  | 800      | Pass        |
| Time of Use Power 2                 |      155       |  10W  | 800      | Pass        |
| Time of Use Power 3                 |      156       |  10W  | 800      | Pass        |
| Time of Use Power 4                 |      157       |  10W  | 800      | Pass        |
| Time of Use Power 5                 |      158       |  10W  | 795      | Pass        |
| Time of Use Power 6                 |      159       |  10W  | 803      | Pass        |
| Time of Use Voltage 1               |      160       |   V   | 2900     | ?           |
| Time of Use Voltage 2               |      161       |   V   | 2900     | ?           |
| Time of Use Voltage 3               |      162       |   V   | 2900     | ?           |
| Time of Use Voltage 4               |      163       |   V   | 2900     | ?           |
| Time of Use Voltage 5               |      164       |   V   | 2900     | ?           |
| Time of Use Voltage 6               |      165       |   V   | 2900     | ?           |
| Time of Use SOC 1                   |      166       |   %   | 30       | Pass        |
| Time of Use SOC 2                   |      167       |   %   | 25       | Pass        |
| Time of Use SOC 3                   |      168       |   %   | 50       | Pass        |
| Time of Use SOC 4                   |      169       |   %   | 60       | Pass        |
| Time of Use SOC 5                   |      170       |   %   | 70       | Pass        |
| Time of Use SOC 6                   |      171       |   %   | 40       | Pass        |
| Time of Use Charge Enable 1         |      172       |       | 1        | Pass        |
| Time of Use Charge Enable 2         |      173       |       | 0        | Pass        |
| Time of Use Charge Enable 3         |      174       |       | 0        | Pass        |
| Time of Use Charge Enable 4         |      175       |       | 0        | Pass        |
| Time of Use Charge Enable 5         |      176       |       | 0        | Pass        |
| Time of Use Charge Enable 6         |      177       |       | 0        | Pass        |

**Hardware (please complete the following information):**
 - Inverter model: Deye SUN-15K-SG01HP3-EU-AM2

![timeofuse](https://github.com/kbialek/deye-inverter-mqtt/assets/32699121/d4d07b21-66a2-45e3-8ca5-036fa01da637)

**Comment by kbialek** [comment]
> * Time of Use Voltage 1-6 I can't make sense of. Even if the unit would be 0.1V, what would 290V mean? The only similar value I could find in my BMS is MIN. Discharge Voltage = 290V (I have 3 modules a 100V so nominal Voltage 307V)

I think, you may use either SOC% or Battery Voltage as a threshold. This is a page taken from the [manual](https://www.deyeinverter.com/deyeinverter/2022/09/15/%E3%80%90b%E3%80%9130240301001287-%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E%E4%B9%A6-%E5%82%A8%E8%83%BD%E4%B8%89%E7%9B%B8-sun-(25-50)k-sg01hp3-eu-bm4-%E5%BE%B7%E4%B8%9A%E8%8B%B1%E6%96%87-%E5%B0%81%E9%9D%A2%E5%BD%A9%E5%8D%B0-%E5%B0%81%E9%9D%A2%E5%B0%81%E5%BA%95157g-%E5%86%85%E9%A1%B570g%E9%93%9C%E7%89%88%E7%BA%B8-142.5x210mm-ver2.2.pdf) 

![image](https://github.com/kbialek/deye-inverter-mqtt/assets/1640028/cdd5ac97-257c-474f-9bd2-2d00a74396e3)



> * unit of Time of Use Power 1-6 is 10W, in contrast to W in the LV settings

So, if I get it correct, the new metric group would look identical to https://github.com/kbialek/deye-inverter-mqtt/blob/main/docs/metric_group_deye_sg04lp3_timeofuse.md (except of power scale factors)
