### ISSUE TITLE
Support for ETH module LSE-3

### ISSUE THREAD

**Issue by TRIROG** [kbialek/deye-inverter-mqtt#181]
Hardware:
Deye SUN-12K-SG04LP3
Hi!

Before buying it, is modbus reading via ethernet module supported or just through wireless?

**Comment by kbialek** [comment]
Good question. I do not own LSE-3. Afaik, modbus/tcp at port 8899/tcp does not work. I do not know if modbus/at at port 48899/udp works. You may try to find the answer at one of the forums like https://www.photovoltaikforum.com or https://diysolarforum.com

Also this thread sheds some light on the topic https://github.com/StephanJoubert/home_assistant_solarman/issues/247
