### ISSUE TITLE
grab last error messages from deye inverter send as MQTT topic

### ISSUE THREAD

**Issue by solarc3po** [kbialek/deye-inverter-mqtt#188]
**Is your feature request related to a problem? Please describe.**
it is possible to grab last error messages from deye inverter via MQTT
![Screenshot_20240726_093053](https://github.com/user-attachments/assets/d1dba19c-939e-458b-8db6-1e77950c02d6)
asume the messages will be aviable as  

date | errorcode (text looks like localisation)

**Describe the solution you'd like**
like the other values, provide messages via mqtt

Again many thanks for your great work.
Since 2 years a stable solution in my IOT stack.

**Comment by kbialek** [comment]
@solarc3po This topic requires research, and I have no time for that at the moment. In case you want to do that, here is an excerpt from the documentation that might be useful.

Modbus registers:
![image](https://github.com/user-attachments/assets/d1ef142d-364b-4941-ab8a-9916c19e5b9d)

Faults table
![image](https://github.com/user-attachments/assets/f4262d4a-ea89-41d1-860b-78d03976ff95)
![image](https://github.com/user-attachments/assets/84804021-77d0-47e9-9091-fd65c2944238)
![image](https://github.com/user-attachments/assets/e069e42a-40b0-4139-a02d-5f0d82a12898)
