### ISSUE TITLE
Access to private methods

### ISSUE THREAD

**Issue by CarstenGrohmann** [kbialek/deye-inverter-mqtt#204]
Hi,

I use a copy of 

https://github.com/kbialek/deye-inverter-mqtt/blob/9b47eaea613d3955735183d3e1f0fb0536c48b24/src/deye_mqtt.py#L112-L116

and 

https://github.com/kbialek/deye-inverter-mqtt/blob/9b47eaea613d3955735183d3e1f0fb0536c48b24/src/deye_mqtt.py#L118-L119

 in my HA plugin to re-create the MQTT topic for each sensor. The code is duplicated to avoid accessing the private functions.

I would like to replace the code in my plugin with a better solution.

I see two possibilities for this:

1. Changing the signatur of both functions to make them public

2. Calculate the MQTT topic once and store it as property in the `Sensor` class. However, I haven't looked at the code very closely to see if this works well with the logger index

What do you think of such a change?

**Comment by kbialek** [comment]
> * Changing the signatur of both functions to make them public

I don't think it's a good idea. My alternative proposal is shown in the PR https://github.com/kbialek/deye-inverter-mqtt/pull/205 It's not yet tested though.

> * Calculate the MQTT topic once and store it as property in the `Sensor` class. However, I haven't looked at the code very closely to see if this works well with the logger index

This is not an option, because Sensor object can be used for multiple inverters when the service runs in microinverter fleet mode
