### ISSUE TITLE
possible to change parameter as well?

### ISSUE THREAD

**Issue by torsteinelv** [kbialek/deye-inverter-mqtt#29]
Is it possible to change parameters on the inverter as well?

**Comment by kbialek** [comment]
Yes, as long you know what you are doing of course :slightly_smiling_face: 
It's documented [here](https://github.com/kbialek/deye-inverter-mqtt#reading-and-writing-raw-register-values)

**Comment by torsteinelv** [comment]
I only want to change the paramenter time of use value on volt dynamicly. Mabey someone can assist me with how this is done so I can do it as safe as possible? My inverter is SUN-5K-SG03LP1-EU with logger 23

**Comment by kbialek** [comment]
@torsteinelv This project is not the best choice for dynamic parameter adaptation. There was a similar question raised before  in https://github.com/kbialek/deye-inverter-mqtt/issues/20 and also another project suggested as a solution. Maybe that will help you
