### ISSUE TITLE
Contact - można się z Tobą skontaktować?

### ISSUE THREAD

**Issue by ciechomir** [kbialek/deye-inverter-mqtt#4]
Na dniach dostanę swojego Deye i szukam możliwości jego monitorowania. U siebie korzystam z Home Assistanta, do którego chciałbym zaciągać dane z DEYE. Jesteś w stanie w tym pomóc?

**Comment by kbialek** [comment]
@ciechomir Nie korzystam z HA, ale widzę że dla HA jest gotowy binding https://github.com/StephanJoubert/home_assistant_solarman 
Tak pewnie będzie najprościej
