### ISSUE TITLE
Compatible inverters

### ISSUE THREAD

**Issue by kbialek** [kbialek/deye-inverter-mqtt#41]
Please report here inverter models that work with this tool. This will let me build a database of compatible inverters. Thanks!

Please report:
1. Inverter model
2. Used metric groups

**Comment by aresius** [comment]
It seems to work with
Model: Deye SUN300G3-EU-230
Firmware: MW3_16U_5406_1.53

**Comment by parkpirat** [comment]
1. Deye SUN1600G3-EU-230
2. micro

-> in general working, not finally tested all collected data
Did you use the file below as base for the different parameters? This file I've received from Deye service last time.

[DEYE_Modbus储能-组串-微逆宁波德业V118.pdf](https://github.com/kbialek/deye-inverter-mqtt/files/11036325/DEYE_Modbus.-.-.V118.pdf)

**Comment by kbialek** [comment]
> Did you use the file below as base for the different parameters? This file I've received from Deye service last time.

Yes, exactly

**Comment by K3vb3rt** [comment]
Model: Deye SUN800G3-EU-230
Firmware: MW3_16U_5406_1.57

Thanks!

**Comment by ivanK0dy** [comment]
Hi @kbialek,

As inverters are just rebranded but same HW, I tested on FU-SUN-5K-G05 (Fuji Solar) and get most of information but I miss data from Mobus connected Meter which data are on registers 150-218: 
PDF Document for Deye at: https://diysolarforum.com/attachments/modbus%E5%82%A8%E8%83%BD-%E7%BB%84%E4%B8%B2-%E5%BE%AE%E9%80%86%E5%AE%81%E6%B3%A2%E5%BE%B7%E4%B8%9Av118-pdf.110709/

Registers dec 150 - 218 ? As I can see your script only pull range 003c-0075.
If i try to read it with your toll I get:
Day Load Power:
docker run --rm --env-file config.env ghcr.io/kbialek/deye-inverter-mqtt r 200
int: 1194, l: 170, h: 4

Meter active power: registers 203 (low) and 204(high) I get:
int: 65027, l: 3, h: 254
int: 65535, l: 255, h: 255

How to pull this second range? Or I should create new instance with new range and only read new registers from that range.
Thank you

**Comment by edvandreas** [comment]
Logger Model: Stick Logger LSW-3 (Wifi)

Inverter Model: Deye Sun 12K SG04LP3 EU 
Firmware: 2005-1128-1807

Works great, reading the data every 10 seconds without problems. Thank you!

**Comment by devil33** [comment]
Works here with 

Model: Deye SUN600G3-EU-230
Firmware: MW3_16U_5406_1.57

Thank you so much!

**Comment by RafaelDuncan** [comment]
> Logger Model: Stick Logger LSW-3 (Wifi)
> 
> Inverter Model: Deye Sun 12K SG04LP3 EU Firmware: [2005-1128-1807](tel:2005-1128-1807)
> 
> Works great, reading the data every 10 seconds without problems. Thank you!

Hello, is it also possible to write data to the Deye Sun 12K SG04LP3 EU?  I want to be able to control the adjustments from Home Assistant

**Comment by marcniedersachsen** [comment]
Thank you very much for this great implementation. I have successfully tested these two ("brand new ?") Micro Inverters:

Deye SUN-M60g3-EU-230
and
Deye SUN-M80g3-EU-230

Metric group = Micro,  (I haven't tested ",settings". Guess that will work too :-)

**Comment by lpunkt66** [comment]
**Works for me with version 2023.06.2**  👍 

Model: Deye SUN800G3-EU-230
Firmware: MW3_16U_5406_1.57
Metric group: micro

Device serial number 3912xxxxxx
Inverter serial number 2303xxxxxx

**Did't work with 2023.05.4**

Thanks very much!!!

**Comment by fakehec** [comment]
Model:Deye 30kW SUN-30K-SG01HP3-EU-BM3 hybrid with battery
Metric: deye_sg04lp3, deye_sg04lp3_battery,deye_sg04lp3_ups

Logger serial number: 2770xxxxxx
Inverter serial number: 2304xxxxxx
Works ok everything except data from PV3

Please implement PV3 line data in deye_sg04lp3

**Comment by Verkalets** [comment]
@kbialek thanks!

**Comment by toleabivol** [comment]
DEYE SUN-8K-SG04LP3-EU
Metrics : deye_sg04lp3,deye_sg04lp3_battery

**Comment by Harry4711** [comment]
Hi congratulation to the project.
Model: Deye SUN800G3-EU-230
Firmware: MW3_16U_5406_2.32-D1
I did create a "deye_sensors_deye_2mppt.py" with the appropriate Value for the above model and intergrated it in your "deye_sensors.py" file as you did with other "deye_sensors_deye_*.py" files.
It worked well in an Home Automation environment developed with FHEM
If you are intereset, I could upload the file and send further information.
I did create own groups to not have to use the "micro" one to be more specific for this model.
Best regard

**Comment by fschwanzara** [comment]
Model: Deye SUN600G3-EU-230
Firmware: MW3_16U_5406_2.32-D1
Metric Group: Micro

**Error:**
```
DeyeModbusTcp - ERROR - Response frame has invalid starting byte
DeyeTcpConnector - DEBUG - Received response frame in 1. attempt: 41542b595a434d505645523d4d57335f3136555f353430365f322e33322d44310d0a0d0a
DeyeTcpConnector - DEBUG - Request frame: a51700104500008fde70e90200000000000000000000000000000103003c003945d4c615
DeyeDaemon - INFO - Reading registers [metrics group: micro, range: 003c-0074]
DeyeDaemon - INFO - Reading start
```

I just wanted to get the MQTT messages to send it over to influxDB/Grafana

**Comment by Harry4711** [comment]
TCP ist Not supported any more with this Software version, pleased use AT !!
See documentation

Am 12. Oktober 2023 09:56:02 WESZ schrieb Florian ***@***.***>:
>Model: Deye SUN600G3-EU-230
>Firmware: MW3_16U_5406_2.32-D1
>Metric Group: Micro
>
>**Error:**
>```
>DeyeModbusTcp - ERROR - Response frame has invalid starting byte
>DeyeTcpConnector - DEBUG - Received response frame in 1. attempt: 41542b595a434d505645523d4d57335f3136555f353430365f322e33322d44310d0a0d0a
>DeyeTcpConnector - DEBUG - Request frame: a51700104500008fde70e90200000000000000000000000000000103003c003945d4c615
>DeyeDaemon - INFO - Reading registers [metrics group: micro, range: 003c-0074]
>DeyeDaemon - INFO - Reading start
>```
>
>I just wanted to get the MQTT messages to send it over to influxDB/Grafana
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/kbialek/deye-inverter-mqtt/issues/41#issuecomment-1759206644
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by voipmonitor** [comment]
Hello, 

I have SUN-50K-SG01HP3-EU-BM4   which has 4 strings - I have two battery towers with two BMS - I have modified deye_sensors_deye_sg01hp3.py and added BMS1, BMS2, bettery1 and battery2 registry and fixed one signed/unsigned parameter. 
[deye_sensors_deye_sg01hp3.zip](https://github.com/kbialek/deye-inverter-mqtt/files/13998908/deye_sensors_deye_sg01hp3.zip)

**Comment by mrlordziemniak** [comment]
Hi i have DTSD422-D3 i can read data, but for example current CT1 when energy is with - value there is still + how to mengae this?
and on all Total Positive Energy CT1 CT2 etc is not correct value, any ideas why?

**Comment by xGDNAx** [comment]
WR BW-MI600 Bosswerk 
MW3_16U_5406_2.32-D1

Micro, settings

**Comment by omgfreezeur** [comment]
Deye SUN-M160**G4**-EU-Q0
SW: MW3_16U_5406_1.59

Micro, settings

I receive all data via MQTT Broken in HA without any errors.
Unfortunately, I have not yet found a way to send a command to set the active_power_regulation via MQTT.
Can anyone give me a hint?

**Comment by xGDNAx** [comment]
https://github.com/kbialek/deye-inverter-mqtt/issues/154

**Comment by SandimL** [comment]
Its working with:

Model: Deye [SUN-4K-G](https://pt.deyeinverter.com/product/single-phase-string-inverter/sun3-6-5-6kg.html)
Firmware: LSW3_15_FFFF_1.0.9E
Metric groups: string

Thank you!

**Comment by jpgnz** [comment]
Model: Deye [SUN-16K-SG01LP1-EU](https://www.deyeinverter.com/product/hybrid-inverter-1/sun12-14-16ksg01lp1-1216kw-single-phase-3-mppt-hybrid-inverter.html)
DEYE_METRIC_GROUPS=deye_hybrid,deye_hybrid_battery,deye_hybrid_timeofuse,settings

Looks to be complete, have left all features at defaults, eg:

```
# DEYE_FEATURE_MQTT_PUBLISHER=true
# DEYE_FEATURE_TIME_OF_USE=false
# DEYE_FEATURE_ACTIVE_POWER_REGULATION=false
# DEYE_FEATURE_SET_TIME=false
```

**Comment by matt-kubica** [comment]
Deye `SUN-20K-SG01HP3-EU-AM2`  (version of [SUN-6/8/10/12/15/20K-SG01HP3-EU-AM2](https://deye.com/product/sun-6-8-10-12-15-20k-sg01hp3-eu-am2-6-20kw-three-phase-2-mppt-hybrid-inverter-low-voltage-battery/)) seems to be working fine with `deye_sg01hp3, deye_sg01hp3_battery, deye_sg01hp3_bms, deye_sg01hp3_ups, settings` metric groups.

Haven't tried writes and features besides mqtt reporting. Configuration was mostly default (apart from the envs I had to change).

**Comment by TRIROG** [comment]
Confirmed  working DEYE SUN-12K-SG04LP3-EU
With TCP settings.
DEYE_METRIC_GROUPS=deye_sg04lp3,deye_sg04lp3_battery,deye_sg04lp3_ups,deye_sg04lp3_timeofuse,deye_sg04lp3_generator

Thank you! Awesome work!

**Comment by CarstenGrohmann** [comment]
## Deye SUN300G3-EU-230

all firmware releases:
```
DEYE_METRIC_GROUPS=micro
DEYE_FEATURE_ACTIVE_POWER_REGULATION=false
DEYE_FEATURE_SET_TIME=true
```

### Firmware: MW3_16U_5406_1.53 till MW3_16U_5406_1.57
Metric groups: micro
Modbus/TCP (default)

### Firmware: MW3_16U_5406_2.32-D1
Metric groups: micro
Modbus/AT

**Comment by BjoernSch** [comment]
SUN-M80G4-EU-Q0
MW3_16U_5406_1.62

Metric groups: micro, settings_micro
Modbus/AT

Metric groups: micro, settings_micro
Modbus/TCP (default)

Settings was not really tested.

**Comment by Bhoft** [comment]
SUN-M160G4-EU-Q0
MW3_16U_5406_1.59

Metric groups: micro,settings_micro
DEYE_LOGGER_PROTOCOL: at

Everythings works perfectly

**Comment by kingp0dd** [comment]
How can we add new sensors to the metric groups? There are additional (grid and load consumption) values that worked on Deye string inverter

Deye SUN-6K-SG05P1-EU-AM2

https://github.com/davidrapan/ha-solarman/commit/12c5d45704764a802a9d6c8a012e6ad28bc760dd

https://github.com/davidrapan/ha-solarman/commit/20e04f14a7fc366831e65e61ed86812e185a0059

**Comment by Pims8383** [comment]
Model : SUN-M100G4-EU-EQ
Firm : MW3_16U_5406_1.62
Metric : micro, settings, deye_micro_systemtime

Working perfectly

**Comment by completelyClueless** [comment]
Model: 20K-SG05LP3-EU-SM2

Metrics: *SG04LP3*

**Comment by averter** [comment]
Model: 10K-SG05LP3
Metrics: all related to SG04LP3 as the registers are pretty much the same
DEYE_LOGGER_PROTOCOL: mbtcp
Logger: waveshare [RS485 TO WIFI/ETH](https://www.waveshare.com/wiki/RS485_TO_WIFI/ETH) for stability. I had massive issues with setting it working right with the plugin. Errors "Modbus frame is too short" and logger timeouts were abundant, and it turned out to be because of a baudrate adaptive setting of the waveshare which had to be disabled (config shared below to help others).

<img width="564" height="1359" alt="Image" src="https://github.com/user-attachments/assets/d6036601-3a93-436b-929c-c66e88376cfd" />

**Comment by joshuwapoot** [comment]
SUN-5K-SG04LP1
LSW3_32_5406_SS_04_00.00.00.0B

**Comment by yaqjav** [comment]
Model: Deye SUN-15K-SG05LP3-EU-SM2
Firmware: LSW3_32U_5406_1.0B
Metric groups: deye_hybrid, deye_hybrid_three_phase, deye_battery_multi
