### ISSUE TITLE
Unbelievable values

### ISSUE THREAD

**Issue by DetlefR** [kbialek/deye-inverter-mqtt#51]
Hello,

at first, thanks for your great work.
I use a SUN-12K-SG04LP3 and it works (almost) fine. Unfortunately, some values are absolutely unbelievable. I found this concerns  "SingleRegisterSensor" register with values they can become negative values. As example the battery  current in case of charging/discarding.
I cannot remember where, but somewhere I have read this values has to treated as signed integer.

I have made a short (and dirty) modification in "deye_sensor.py" in SingleRegisterSensor class.
This shows values they are more  trustful.
´´
           retval = int.from_bytes(reg_value, 'big')
            if retval>32767:
                retval=retval-65536
            #return int.from_bytes(reg_value, 'big') * self.factor + self.offset
            return retval * self.factor + self.offset
´´
Best regards
Detlef

**Comment by kbialek** [comment]
@DetlefR Yes, this sounds about right. I had a similar suspicion, and described it here https://github.com/kbialek/deye-inverter-mqtt/issues/47#issuecomment-1483890552

I do not own SG04LP3, so I couldn't verify it on my own. Now with your report I'm sure how to fix it. Thanks.

**Comment by kbialek** [comment]
Fixed version is out https://github.com/kbialek/deye-inverter-mqtt/releases/tag/2023.03.4

**Comment by DetlefR** [comment]
I have tested it. For me, it's working well.
Thank you.

BTW: A wish for the next greater change. Please divide date from code. See deye_sensors_deye_sg04lp3.py. Put the config data to a separate file.
