### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by schnello** [kbialek/deye-inverter-mqtt#54]
Hello.

Thank you for this project and your work.
As docker newbie:
What is the prefered way to "autostart" Systemctl Service? Screen?

Christian

**Comment by kbialek** [comment]
I'm not sure what you are asking about :slightly_smiling_face: Anyway, let me try to answer
1. docker autostart - I've updated the docs, check it out [here](https://github.com/kbialek/deye-inverter-mqtt/commit/2067e47a297e4d8c4638e28e91b7d1a3f44ce62b)
2. systemd autostart - `systemctl enable <unit-name>`

**Comment by schnello** [comment]
Thanks.
