### ISSUE TITLE
Compatability with secure-mqtt

### ISSUE THREAD

**Issue by devil33** [kbialek/deye-inverter-mqtt#62]
Hi there,

I just started off using the nice piece of software to store my readings locally.

For my MQTT broker I use mosquitto with port 8883, secure-mqtt.
I would like to know if there are plans to implement

a) Full secure-mqtt support with custom CAs
b) secure-mqtt with options to at least ignore TLS verification errors.

I can type down some python but would not consider myself a programmer.
Nevertheless, I like to offer my help if needed.

Thanks
devil33

**Comment by kbialek** [comment]
This will have to wait until I have time to implement it.

**Comment by kbialek** [comment]
@devil33 

Could you test this beta image? `ghcr.io/kbialek/deye-inverter-mqtt:2023.04.2-beta-2`

Instructions: https://github.com/kbialek/deye-inverter-mqtt/tree/feature/mqtt-tls#connecting-to-mqtt-broker-over-tls

**Comment by kbialek** [comment]
correct, that's mtls
