### ISSUE TITLE
CT-Power missing

### ISSUE THREAD

**Issue by hackepeterOli** [kbialek/deye-inverter-mqtt#63]
Hi @kbialek,

is it possible to implement the following values?

The inverter is: SUN-10K-SG04LP3-EU

Here are the definitions from HomeAssistent:

    - name: "Internal CT L1 Power"

      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x025C]

    - name: "Internal CT L2 Power"
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x025D]
      
    - name: "Internal CT L3 Power"
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x025E]

    - name: "External CT L1 Power"
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x0268]

    - name: "External CT L2 Power"
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x0269]
      
    - name: "External CT L3 Power"
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x026A]

**Comment by kbialek** [comment]
@hackepeterOli 
Sure, what is CT? What mqtt topic suffixes would you propose for these metrics?

**Comment by hackepeterOli** [comment]
Here one test with Internal CT L1:

Home Assistent reading: 479 W

  docker run --rm --env-file config.env ghcr.io/kbialek/deye-inverter-mqtt r 604
  2023-04-20 14:58:38,831 - DeyeConnector - DEBUG - Request frame: 
  a517001045000065d7588e0200000000000000000000000000000103025c000145a0d815
  2023-04-20 14:58:38,895 - DeyeConnector - DEBUG - Response frame: 
  a515001015005465d7588e02014be058002f1a0000d272e863010302fd8138b47e15
  int: 64897, l: 129, h: 253

**Comment by kbialek** [comment]
@hackepeterOli  `64897` represents a negative value. Please check the PR above

**Comment by hackepeterOli** [comment]
Sorry, i dont know how to get a docker container from the pull request :( - or edit the files in my docker container

**Comment by kbialek** [comment]
@hackepeterOli By "check" I meant to "have a look and verify" the change :slightly_smiling_face: 

Anyway, to keep it simple, here you have a beta image `ghcr.io/kbialek/deye-inverter-mqtt:2023.04.2-beta-1` that contains this change

**Comment by hackepeterOli** [comment]
@kbialek Sorry, i am a newbie at github - but i am trying to become better and better...

Holy shit, it works! The readings are correct! you are my personal photovoltaic god!

    ac/l1/ct/external | 14.0 | 2023-04-20 22:28:54
    ac/l1/ct/internal | -229.0 | 2023-04-20 22:28:54
    ac/l2/ct/external | 0.0 | 2023-04-20 22:28:54
    ac/l2/ct/internal | -86.0 | 2023-04-20 22:28:54
    ac/l3/ct/external | 11.0 | 2023-04-20 22:28:54
    ac/l3/ct/internal | -169.0 |  

I miss another reading called micro inverter input (gen port) - but that's another topic - and i didn't find it in the home assistant either. You can close this enhancement!

**Comment by kbialek** [comment]
> you are my personal photovoltaic god!

Good one! :smile:
