### ISSUE TITLE
reopening/reviewing start information

### ISSUE THREAD

**Issue by parkpirat** [kbialek/deye-inverter-mqtt#68]
Hi,
just a short question:
After starting the container without "-d",  different information will occur, depending on the log level.
How can I see this information again, after closing the terminal window? Meaning: How I can see this, when the container is already running? Is there a command which I can use?

Thank you.

Regards,
Carlo57

**Comment by kbialek** [comment]
Sure, README updated https://github.com/kbialek/deye-inverter-mqtt#option-1-using-docker-directly
