### ISSUE TITLE
Disable MQTT server requirement when starting with DEYE_FEATURE_MQTT_PUBLISHER=false

### ISSUE THREAD

**Issue by ndi123** [kbialek/deye-inverter-mqtt#70]
I currently use the Docker container only to set the time to reset the daily production. For this reason i start the docker container with the parameters `DEYE_FEATURE_MQTT_PUBLISHER=false` and `DEYE_FEATURE_SET_TIME=true`

I expected that i would not need a running MQTT server when using `DEYE_FEATURE_MQTT_PUBLISHER=false`, but the Docker container does not start if no MQTT server is reachable.

Suggestion: Disable the requirement to have a running MQTT server, when using `DEYE_FEATURE_MQTT_PUBLISHER=false`.

**Comment by kbialek** [comment]
Fixed in version 2023.05.1
